### PR TITLE
Handle ignored children in decorate

### LINKED ISSUE #839: Test renderer: can't call property for conditional wrapped node
**Bug** 

`r.property(WrappedNode, 'propName')` does not work for a node that is not expected in the next assertion

Package Version: 7.0.3

**Code**

(See [`FileUploadInput` test](https://github.com/msssk/widgets/blob/0ec69738e2eb946da84b7e4c79010cad7d094765/src/file-upload-input/tests/unit/FileUploadInput.spec.tsx#L152-L185))

```typescript
	it('handles dragenter, dragleave, and the overlay', function() {
		const r = renderer(function() {
			return <FileUploadInput />;
		});
		const WrappedOverlay = wrap('div');

		r.expect(baseAssertion);
		r.property(WrappedRoot, 'ondragenter', { preventDefault: noop });

		r.expect(
			baseAssertion
				.setProperty(WrappedRoot, 'classes', [
					null,
					fixedCss.root,
					css.root,
					css.dndActive,
					false
				])
				.append(WrappedRoot, function() {
					return [
						<WrappedOverlay
							key="overlay"
							classes={[fixedCss.dndOverlay, css.dndOverlay, false]}
							ondragleave={noop}
						/>
					];
				})
		);

		r.property(WrappedOverlay, 'ondragleave');
		r.expect(baseAssertion);
	});
```

**Expected behavior:**

`ondragleave` should be triggered on `WrappedOverlay`

**Actual behavior:**

`ondragleave` is not triggered

### PR DESCRIPTION
**Pull request by maier49**
**Type:** bug

The following has been addressed in the PR:

* [ ] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**
Allows finding wrapped nodes when the actual array has additional children that are undefined or booleans.

This fix resolves the failure that led to #839 being created, but the actual bug was not what we originally thought.
Resolves #839

### CODE REVIEW

File: tests/testing/unit/renderer.tsx [hunk 1]
```diff
@@ -222,6 +239,19 @@ describe('test renderer', () => {
 			);
 		});
 
+		it('trigger property when there are undefined children in actual render', () => {
```
Comment (msssk) [inline tests/testing/unit/renderer.tsx:242]: would "triggers property" be better?

File: tests/testing/unit/renderer.tsx [hunk 2]
```diff
@@ -222,6 +239,19 @@ describe('test renderer', () => {
...
+			const WrappedRoot = wrap('div');
+			const WrappedChild = wrap('div');
+			const WrappedConditional = wrap('div');
+			const baseTemplate = assertion(() => w(WrappedRoot, {}, [w(WrappedChild, { onclick: noop })]));
```
Comment (agubler) [inline tests/testing/unit/renderer.tsx:246]: If you're using wrapped vnodes with the functional API we should be using `v()` and then calling `.tag` from the WrappedNode - `v(WrappedRoot.tag` - alternatively using TSX. I thought there was mention of this in the docs but I can't find it.

File: tests/testing/unit/renderer.tsx (hunk 1 above)
Comment (maier49) [reply tests/testing/unit/renderer.tsx]: Yeah that sounds better

**Review by matt-gadd — APPROVED** [review]
