### PR TITLE
Fix length return for immutable lists

### LINKED ISSUE #343: `ImmutableState` not returning correct values for array length
**Bug** 

Package Version: 6.0.0-alpha.1

The Immutable lists internally use `size` instead of `length`, and the ImmutableState implementation is not currently handling that to return the correct value.

### PR DESCRIPTION
**Pull request by maier49**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**
Adds logic to convert Immutable List size to array length 
Resolves #343

### CODE REVIEW

File: tests/stores/unit/state/ImmutableState.ts [hunk 1]
```diff
@@ -214,6 +214,17 @@ describe('state/ImmutableState', () => {
 		});
 	});
 
+	it('should report the length of an array', () => {
+		const state = new ImmutableState();
+		state.apply([{ op: OperationType.ADD, path: new Pointer('foo'), value: [] }]);
+
+		assert.equal(state.path('foo', 'length').value, 0);
```
Comment (agubler) [inline tests/stores/unit/state/ImmutableState.ts]: Do you think we should use `state.get` to actually return the value?

Comment (maier49) [reply tests/stores/unit/state/ImmutableState.ts]: Fair enough, I've updated this. Though it is a bit funny to replace `path.value` with a call to `get` that's just returning `path.value` anyways. Maybe at some point we should evaluate whether `state.get` will ever have merit a more useful implementation and if not, consider removing it?
