### PR TITLE
Convert `Outlet` from a HOC to a standard component with a render prop

### LINKED ISSUE #60: Convert `Outlet` to use a render prop to describe the output
**Enhancement**

An `Outlet` is a basic higher order component which accepts one or more widgets on creation of the outlet. 

```ts
// separate outlet component file

export const MyOutlet = Outlet({
    index: IndexWidget, 
    main: MainWidget, 
    error: ErrorWidget }, 'outlet-name'):
```

The current implementation is problematic for typings when there are multiple widgets specified as the `Outlet`'s properties becomes a union type of all the widget's properties passed to the `Outlet`. This is not correct, as you may need to pass different values for the same property depending on the match type scenario. Another side affect means that widgets could receive extra properties that were intended for a different widget.

There are at least a couple of potential options:

#### Option 1

Move from a HOC to a component that accepts a render property to describe the outlets output. This will allow consumers to explicitly pass the properties to each of the widgets and give more control to the consumer to create customised logic on which widgets to display.

```ts
// inside your widget
render() {
    return v('div', [
        w(Outlet, { 
            to: 'outlet-name', 
            renderer: (matchDetails) => {
                // match details contains the `matchType`, `params` and `queryParams`
                return w(MyWidget, { foo: 'bar', id: matchDetails.id });
            }
        })
    ]);
}
```

#### Options 2

Keep with a HOC to a component but one that accepts a render function to describe the outlets output. This will also allow consumers to explicitly pass the properties to each of the widgets and give more control to the consumer to create customised logic on which widgets to display.

```ts
interface MyOutletProperties {
    foo: string;
}

const MyOutlet = Outlet<MyOutletProperties>((properties, outletProps) => {
     if (outletProps.isError()) {
        return w(ErrorWidget, {});
     }
     if (outletProps.isExact()) {
         return w(ExactMatchWidget, {});
     }

     // return undefined when no widget is needed to be rendered based on the match type.
     return undefined;
}, 
{ outlet: 'foo' })
```

### PR DESCRIPTION
**Pull request by agubler**
**Type:** feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**

This changes the `Outlet` from a higher order component to a standard component with a render property. The render property is used to display content when a route matches providing more control over the nodes to render when an Outlet's route has been matched.

Having an `Outlet` as a HOC implies that it would be shared across the application (which generally they are not), adds complexity in it's usage by having to specify another interface for the properties that the `Outlet` can accept and has more boilerplate and indirection that if the `Outlet` is a standard widget.

```ts
render() {
    return v('div', [
        w(Outlet, { 
            id: 'outlet-name', 
            renderer: (matchDetails: MatchDetails) => {
                // match details contains the `matchType`, `params` and `queryParams`
                return v(MyWidget, { foo: 'bar', id: matchDetails.id });
            }
        })
    ]);
}
```

Resolves #60 

Alternative to #24

### CODE REVIEW

File: src/routing/interfaces.d.ts [hunk 1]
```diff
@@ -129,42 +123,37 @@ export interface OnExit {
...
 }
 
-/**
- * Outlet options that can be configured
- */
-export interface OutletOptions {
-	key?: RegistryLabel;
-	mapParams?: MapParams;
-}
+export interface MatchDetails {
```
Comment (agubler) [inline src/routing/interfaces.d.ts]: Is `OutletDetails` a better name?

Comment (tomdye) [reply src/routing/interfaces.d.ts]: I think `MatchDetails` is more appropriate as it's the details for the current match, not the outlet as a whole. Perhaps `MatchProperties` though?

File: src/routing/Outlet.ts [hunk 2]
```diff
@@ -1,100 +1,97 @@
...
+import { MatchDetails, OnExit, OutletContext, OnEnter, Params } from './interfaces';
 import { Router } from './Router';
+import { diffProperty } from '../widget-core/decorators/diffProperty';
+import { Handle } from '../core/Destroyable';
 
-export function isComponent<W extends WidgetBaseInterface>(value: any): value is Component<W> {
-	return Boolean(value && (typeof value === 'string' || typeof value === 'function' || typeof value === 'symbol'));
+export interface OutletProperties {
+	renderer: (matchDetails: MatchDetails) => DNode;
+	outlet: string;
```
Comment (tomdye) [inline src/routing/Outlet.ts]: perhaps rename to `id` ?

File: src/routing/Outlet.ts [hunk 3]
```diff
@@ -1,100 +1,97 @@
...
-import { OnEnter, Component, OutletOptions, OutletComponents, Outlet, Params, OutletContext } from './interfaces';
+import { MatchDetails, OnExit, OutletContext, OnEnter, Params } from './interfaces';
 import { Router } from './Router';
+import { diffProperty } from '../widget-core/decorators/diffProperty';
+import { Handle } from '../core/Destroyable';
 
-export function isComponent<W extends WidgetBaseInterface>(value: any): value is Component<W> {
-	return Boolean(value && (typeof value === 'string' || typeof value === 'function' || typeof value === 'symbol'));
+export interface OutletProperties {
+	renderer: (matchDetails: MatchDetails) => DNode;
```
Comment (tomdye) [inline src/routing/Outlet.ts]: Can this not return an array of `DNodes` ?

File: src/routing/interfaces.d.ts (hunk 1 above)
Comment (agubler) [reply src/routing/interfaces.d.ts]: Don't want to overload `properties`

File: src/routing/Outlet.ts (hunk 3 above)
Comment (agubler) [reply src/routing/Outlet.ts]: I think it should be able to.
