### PR TITLE
Throwing an error on missing selector in test harness trigger

### LINKED ISSUE #318: Test harness should throw on missing selectors
**Enhancement** 
The testing harness should throw when the selector isn't found. Th.is would help debug failing tests

Package Version: 

**Code**
```typescript
h.trigger('@nonExistantSelector', 'whatToTrigger');
```

**Expected behavior:**
The trigger call will throw an error indicating the selector could not be found.

**Actual behavior:**
The trigger passes silently.

### PR DESCRIPTION
**Pull request by rorticus**
**Type:** bug / feature

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**

Instead of silently failing, throwing an error when a `h.trigger` encounters a selector that doesn't return any nodes.

Resolves #318

### CODE REVIEW

File: src/testing/harness.ts [hunk 1]
```diff
@@ -133,16 +133,19 @@ export function harness(
...
-					triggerFunction = (firstItem.properties as any)[functionSelector];
-				} else {
-					triggerFunction = functionSelector(firstItem);
-				}
-				if (triggerFunction) {
-					return triggerFunction.apply(widget, args);
-				}
+
+			if (!firstItem) {
+				throw new Error(`Cannot find node with selector ${selector}`);
```
Comment (aciccarello) [inline src/testing/harness.ts]: I like this error message. It might be good to make this and the assertion template errors consistent.

https://github.com/dojo/framework/blob/4526fecf0feb91df26ad8f3a8f030f13822dff71/src/testing/assertionTemplate.ts#L36

Comment (rorticus) [reply src/testing/harness.ts]: I don't disagree, but updating the message there is a bit more complicated. I've made the change though, we'll see how it goes 😄

File: src/testing/assertionTemplate.ts [hunk 2]
```diff
@@ -26,21 +26,19 @@ const findOne = (nodes: DNode | DNode[], selector: string): DNode | undefined =>
...
-
-type NodeWithProperties = (VNode | WNode) & { properties: { [index: string]: any } };
 
-const guard = (node: DNode): NodeWithProperties => {
 	if (!node) {
-		throw Error('Node not found');
+		throw Error(`Cannot find node with selector ${selector}`);
 	}
 	if (!isWNode(node) && !isVNode(node)) {
 		throw Error('Cannot set or get on unknown node');
```
Comment (matt-gadd) [inline src/testing/assertionTemplate.ts]: Hmm I don’t think we should change this. The findOne is meant to be equivalent to querySelector and not throw. It also doesn’t make sense to throw a setting unknown node here given the function name?

Comment (rorticus) [reply src/testing/assertionTemplate.ts]: Hehe, yeah, I wasn't sure about these changes. The other option is i can pass the selector in `guard` so it can use it in the error message, but thats going to end up looking silly and be a bit of a pain every time you call it.  Maybe i should just remove that last commit?

Comment (matt-gadd) [reply src/testing/assertionTemplate.ts]: Ha yeah I agree, maybe for now we just stick with the trigger change and we can raise a separate issue for making error messages more consistent (it might be that we use the same function in the harness and assertion template)
