### PR TITLE
Fixes: Routing and Link Fixes

### LINKED ISSUE #145: Routing: Navigation to default route should be syncronous
**Bug**

Navigating to a default route hands off responsibility to the history adapters which use the appropriate mechanism, when using the `HashHistory` this uses the `hashchange` event which is asynchronous.

When calling the `router` instance's `setPath()` explicitly we should synchronously process the change and guard against repeated (surplus) processing in the adaptors.

### LINKED ISSUE #146: Routing: The router should generated correctly formatted links
**Bug**

`router.link()` generates links without the required prefix for the chosen adaptor. The correct prefix should be applied during the link generation.

### LINKED ISSUE #147: Routing: CTRL/CMD click should open the a `Link` in a new window
**Bug**

Currently links generated by the `Link` component do not support using `cmd` or `ctrl` (depending on the operating system) to open the link in a tab.

### PR DESCRIPTION
**Pull request by agubler**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**

A collection of fixes for the routing:

* Support ctrl/cmd click
* Ensure links are generated with appropriate prefixes
* Ensure routing is synchronous with `setPath` when using `HashHistory`
* Strip leading `#` character when using `StateHistory`

Resolves #147 
Resolves #146 
Resolves #145

### CODE REVIEW

File: src/routing/history/StateHistory.ts [hunk 1]
```diff
@@ -14,26 +28,26 @@ export class StateHistory implements HistoryInterface {
...
-		if (baseEndsWithSlash && pathStartsWithSlash) {
-			return this._base + path.slice(1);
-		} else if (!baseEndsWithSlash && !pathStartsWithSlash) {
-			return `${this._base}/${path}`;
-		} else {
-			return this._base + path;
+		if (path[0] === '#') {
+			path = path.slice(1);
+		}
+		if (path[0] === '/') {
```
Comment (matt-gadd) [inline src/routing/history/StateHistory.ts]: this can be one if with the above right?

Comment (agubler) [reply src/routing/history/StateHistory.ts]: I did it this was to guard against `#/link` which needs to be `link`
