### PR TITLE
Emit the routing event after the routing has been completed

### LINKED ISSUE #136: Routing does not work when the renderer is in sync mode
**Bug**

When the projector is in sync mode then the components for outlets and links (anything related to routing) actually re-render before the routing navigation is actually completed. Meaning that an application is not correctly rendered.

### PR DESCRIPTION
**Pull request by agubler**
**Type:** bug

The following has been addressed in the PR:

* [x] There is a related issue
* [x] All code has been formatted with [`prettier`](https://prettier.io/) as per the [readme code style guidelines](./../#code-style)
* [x] Unit or Functional tests are included in the PR

**Description:**

Ensure that the routing events are emitted after the routing navigation is completed.

Resolves #136

### CODE REVIEW

File: tests/routing/unit/ActiveLink.ts [hunk 1]
```diff
@@ -244,4 +249,58 @@ describe('ActiveLink', () => {
 
 		assert.deepEqual(dNode2.properties.classes, []);
 	});
+
+	jsdomDescribe('integration tests', () => {
```
Comment (dylans) [inline tests/routing/unit/ActiveLink.ts]: should this be `describe`, not `jsdomDescribe`? Perhaps I'm misunderstanding, but I thought `jsdomDescribe` was the type here?

Comment (agubler) [reply tests/routing/unit/ActiveLink.ts]: Nope, this is the plugin to use jsdom.
